apiVersion: v1
kind: Pod
metadata:
  name: mongo-debug
  namespace: habitica
spec:
  containers:
    - name: debug
      image: busybox
      command:
        - sh
        - -c
        - sleep 3600

      volumeMounts:
        - name: mongo-data
          mountPath: /data/db

  volumes:
    - name: mongo-data
      persistentVolumeClaim:
        claimName: mongo-data
