apiVersion: v1
data:
    password: ENC[AES256_GCM,data:uw6dHx6il/rVgwLM/BeveUUUMdqWIGKTdNrA9A==,iv:oLs3Tg59pMm+x/+pCX8UtXgZJUWHq2lKkpGkFffnzYs=,tag:cjQHEQUdKRRGbJgOV37lyQ==,type:str]
    user: ENC[AES256_GCM,data:w44uGyOUqR8=,iv:xYDIFvzlCqkVPuP85UIIQs1uvdNaWYDsK3GHXzQolr0=,tag:sVdHqdfpEFOXddfC3litRw==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-07-13T12:51:50Z"
    name: test-secret
    namespace: default
    resourceVersion: "61917571"
    uid: e7aa7ca7-4ba3-4132-8bda-4d4c6cbfd3f6
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUzl2SEw4eDJSL0p3SUhn
            ZDdwaUUrVTFvd3dQN2pPUllCaTVrYjMvMTFBCkQyaTJEODF5MXpYMGY0QVM2MzRJ
            SE55cW1NRk9RUnJMVXhyMk5qR0s1R0kKLS0tIExFSlUydDZUWkJBWUh2RllwWWNL
            NUxwUGdrYUk4T0Zxak9ib2xraWVxYU0KQa/3CYSoSHV+PIq7hcPFmdsPeYtq5QiJ
            cBlRVOxl/in6BTRVIP5BaqnZ/rOIO7FCc060YclH+DHf3hqE2nNyMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejdagdnt3k97usm9mcxz62svvuh27tqqaj6hr45mv2urg4azhpls3zxf7g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T12:56:08Z"
    mac: ENC[AES256_GCM,data:W0RLeo+IpdqWQe3QQPdF1FoWLg+oTV1MXkceEyTWhHIP8bAg9q45X0qUsrJsNVtGM58wEsVo8lHL/7OwgA58MpvT6JwlI6mM3dgjXDbJtagJr+CnWWw9k3KuiwYndTTH3wqyi36feq9UBJSU5mePnhXzXlmnk9QM5m0VnVVBulo=,iv:oKbRCrmGZi5VApaFkuDFd1vXkOsQeclD2BZJWPoO4AU=,tag:F11vQvO9LgoeqrEX6iZ7mg==,type:str]
    version: 3.13.2
