apiVersion: v1
data:
    password: ENC[AES256_GCM,data:T/gnRn4348U=,iv:6hTFwZcoCCbBGUA9Cw8dlvAlE+JN8SV4p4OHrPpgoXs=,tag:jebpi5GFPoxuVU8fL9HJ2Q==,type:str]
    user: ENC[AES256_GCM,data:w4dSITnMqqM=,iv:JkXA1qNqFIDm5lyndvXgkg8goQK4V/oz1XSWKuuHnfU=,tag:5G73ovD6vhSbcJ/9aq1r8w==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SmJteGNmWDBXdGlhSmVL
            V1kwaUJmaTdCZFRyWWpoWk5hVUZabkRoYlVVCkhCT0FIYjVDTHpEZzFGbVFUSmdj
            K1NHRGFiSFNZQ2dNR0ltSHFWMXJDajQKLS0tIFBCZUY3YU5TSktqbTd1cXpJekRL
            bndBczZZOEhscGIvUnJyaklNeGdiSVkKp92IdF1y8nntapw6IReDpTkLjpj5Jq+Q
            LvM5YTY52ERwpzBZNqqHzVae+RkHQamyoUaQbkjr8emnsb5NjgUYnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd5n9zx0dsdwdggjuvz32ppngn45gk0tcnwlwfs53ev7szefmdfqarudsl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T13:00:57Z"
    mac: ENC[AES256_GCM,data:XzO/7DLxlHbfIKC4e0diTvxBFlTl4lFasXF0+7tPeR4o5kARWL0x7LvouyKjN0wwcDetTpC1XqXFsVpQnqBS/wyAzMsHX9XTCOeH4hPcF1bNLfmTPOsvFN4qGfTYYMuwMGg64L0LKnJ1+Z9STtdNGRUs+1WpVrTpgVf3t1yOpTU=,iv:Pw84LH67oyG2dLXyAYjsxoQnYNlEsveSdIyd7as0U8E=,tag:gh5ijD33TiZ9tvj3saYmHQ==,type:str]
    version: 3.13.2
