apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 10Ti # Match your ZFS pool size or larger
  accessModes:
    - ReadOnlyMany # Or ReadWriteMany if Jellyfin needs to delete/move files
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: jellyfin-media-share
    volumeAttributes:
      source: "//192.168.4.143/mnt/media"
      #source: "//192.168.5.237/mnt/nas/zzremoteserver"
    nodeStageSecretRef:
      name: smb-creds
      namespace: jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Ti
  volumeName: jellyfin-media-pv
  storageClassName: "" # Bind to the static PV above

