apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/linkding
  - ../base/habitica

# Add this section to fix the linkding error
# It ensures everything from the linkding folder goes into the linkding namespace
patches:
  - target:
      group: apps
      kind: Deployment
      name: linkding
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: linkding

