apiVersion: v1
data:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:HoSmuTx8gj08KVhaqNAszNf0YIOnxOlVs+M6aLnw6xzUae6oTMSIxss1QiY0ciimOpBSuShbmG84GzAT3rWMLAbTKmFBdAG7H2GSmCpeWmOpy88mLFO561quHaTvYc7Z,iv:sEHK5JH83vpljf3mcJH8XONf+82bHqVZ0tyJy+QEnsk=,tag:5M5AopPXbdVO16t9C418+w==,type:str]
    DISCORD_GUIDE_CHANNEL_ID: ENC[AES256_GCM,data:KLVoAUC1N14wg8DeFgK/Tfgtt5gxCsyLce+fsw==,iv:cSmi7zgXfs5cU989MbXh/+hbJcgzbRXPsYpumGmRic4=,tag:2nc4n6hBzJt8dObHpgMESA==,type:str]
    DISCORD_GUILD_ID: ENC[AES256_GCM,data:oYDO2mDQKQNn26a1fu78z13hv94bjI4xf2ctgQ==,iv:6vXY/UYE94NCf9ccNjpXCrs3tm5oH43u3YEHf+Lg+Ow=,tag:vgHIs51qjW8Aj69zg7ge4Q==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:dsKpxFS7HvkPg7FUKls6qkiX4H+M2uKI6I5TBa/5S3x0whIGd6nvFtjfYk+0YXY3wFra1cmyyO9sKszUv3VvUJD8o9cqeAaZtHq6oMja4Ld191gNrR16KP2X9VkSiI6d/yWmFUoT7TKIR6pm3G9w2Y5ntByWF3IrPD1D+38Wi4yoR9J3Co3afMFJpsi/IEcDdLcLw6LC7BLrfqL3CR3KjUbK5rHEt6VGxPQz7+nJnP3G3eqjigzuIvW9nEc1Aq+MnSQPPr9OOp2dsCXNBP2MjH2iOr5K1iznYg4DYA==,iv:WgPPRaRPr9zcKmIjh/1kodHSadHqkfgjXvHtbXWdUrE=,tag:5bbV78U0CdyAP/WJXr5Efg==,type:str]
    OPENAI_MODEL: ENC[AES256_GCM,data:CpcgMc3ZLint0sCdJm8sZA==,iv:wigt2UupVjwu3VtJLiPKogPNwHQWzjvRHck94vEAkeY=,tag:WkbvQFOFkHPBa/oqyK9d2g==,type:str]
kind: Secret
metadata:
    name: plugin-doc-bot-secrets
    namespace: plugin-doc-bot
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeG1sTndFZ2RQUzF6dzcv
            MmxFYURrVHVwRmlvNVI5cWlLUmJMYWZRSGpzCndOdXhUYVlOSmF5TlRucEkxcHJt
            VEprRHVHQzZuUjAySW9YM0RmUHNrWXMKLS0tIDhzT0FEYzJibmFYUFBOWC9DeDN2
            RFNjallFeUMrMFRFSTgvbk40dFRnVW8K9/BbXz2so09bWWOFpR0I2zBIDIZDSXuw
            rILZWk0H5DfFIjCe+v96SaP0UCGg/4WCtUgxnnbNFLqi5Nlh2CxHjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejdagdnt3k97usm9mcxz62svvuh27tqqaj6hr45mv2urg4azhpls3zxf7g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T01:59:10Z"
    mac: ENC[AES256_GCM,data:rRwMHdCDs/UwS8qZPtRHL0G5Ok/tybekwh2iS47WNzHYnDd4rwXmKNC4K7i0WuRjSgQyfts0KcKOKiBgI1V9Df1CVqsGHODNl1d8MUPltUChbrlUEqvewhCn6MH790OO09wycE4m84WrCbcgM2h8E8OdtbhmVvn2qDtveMp+hrw=,iv:ntnfRFgL4ErVa1AlPpI+Mbx4y5ywoc4IO7V6QJ2XYKU=,tag:Eo9abvf++DeEEoSSuEa0eA==,type:str]
    version: 3.13.2
