apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  resources:
  - habitica
  - linkding
    # - jellyfin  # Correct: points to the subfolder in the current directory




  #resources:
  #  - namespace.yaml
  #- storage.yaml
  #- deployment.yaml

