apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: habitica
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

